#
# this function creates a BS, base station
#
import matplotlib.pyplot as plt
from ParameterConfig import *
from BroadcastingPacket import BroadcastingPacket

class myBS:
    def __init__(self, id):
        self.ID = id
        # two-dimensional location 
        self.x = 0
        self.y = 0
        self.HopCount = 0
        self.period = avgSendTime
        
        self.packet = None # packet generated by node each time period
        
        self.cf = 868000000
        self.sf = 7
        self.bw = 500
        self.tp = 14
        
        self.ChildSet = []  # list of child nodes
           
    def Generate_AskJoin(self):
        self.packet = None
        
        PacketPara = LoRaParameters()
        PacketPara.cf = self.cf
        PacketPara.sf = self.sf
        PacketPara.bw = self.bw
        PacketPara.tp = self.tp
        self.packet = BroadcastingPacket(self.ID, PacketPara)
        
