#
# this function creates a node
# generate a node in the network with a random space
import matplotlib.pyplot as plt
import numpy as np
from ParameterConfig import *
from DirectionalPacket import DirectionalPacket
from BroadcastingPacket import BroadcastingPacket
from Allocation import *
from Propagation import *
import math

class myNode:
    def __init__(self, id, x, y, period):
        self.ID = id
        self.period = period
        self.HopCount = 0
        
        self.agent = None

        self.x = x
        self.y = y
        self.DisttoGW = math.sqrt(x**2 + y**2)  # distance from the gateway
        self.DistID = None
        self.BatteryCapacity = 1500  # initial battery capacity
        self.ChildSet = [] # list of child nodes
        self.ParentSet = [] # list of parent nodes
        self.ParentFreSet = {} # dictionary to store frequencies corresponding to each ParentNode

        # LoRa parameters the node used to send packets      
        self.sf = 7
        self.bw = 125
        self.cf = 868000000
        self.tp = 14
        
        self.NumSent = 0 # number of packets sent by the node
        self.NumLost = 0 # number of packets lost by the node
        self.NumReceived = 0 # number of packets sent by the node
        
        
        self.JoinReqSet = [] # list of JoinReq packets sent by the node
        self.JoinConfirmSet = [] # list of JoinReq packets sent by the node
        self.RelayPackets = {}
        
        self.PDR = None # Packet Delivery Ratio for the node

        self.packet = None # packet generated by node each time period
        
        self.dist = None

        self.sent = 0

    def Generate_AskJoin(self):
        self.packet = None
        
        PacketPara = LoRaParameters()
        
        PacketPara.sf = self.sf
        PacketPara.bw = self.bw
        PacketPara.cf = self.cf
        PacketPara.tp = self.tp
        self.packet = BroadcastingPacket(self.ID, PacketPara)
    
    def Generate_JoinReq(self):
        self.JoinReqSet = []
        
        PacketPara = LoRaParameters()
        
        PacketPara.sf = self.sf
        PacketPara.bw = self.bw
        PacketPara.cf = self.cf
        PacketPara.tp = self.tp
        
        for ParentNode in self.ParentSet:
            self.dist = get_distance(self.x, self.y, ParentNode)
            self.JoinReqSet.append(DirectionalPacket(self.ID, ParentNode.ID, PacketPara, self.dist))
            
    def Generate_JoinConfirm(self):
        self.JoinConfirmSet = []
        
        PacketPara = LoRaParameters()
        
        PacketPara.sf = self.sf
        PacketPara.bw = self.bw
        PacketPara.cf = self.cf
        PacketPara.tp = self.tp
        
        for index, ChildNode in enumerate(self.ChildSet):
            self.dist = get_distance(self.x, self.y, ChildNode)
            PacketPara.cf = Carrier_Frequency[index % len(Carrier_Frequency)]  # Cycle through frequencies
            self.JoinConfirmSet.append(DirectionalPacket(self.ID, ChildNode.ID, PacketPara, self.dist))
    

